server:
  port: 8080

spring:
  application:
    name: oauth-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: <signing-key>
  encoding-strength: 256
  security-realm: <security-realm>

